### ISSUE TITLE
브랜치에 올린거 메인으로 넘기는법 아시는분 알려주세요(문제해결)

### ISSUE THREAD

**Issue by koeun23** [kingofgeneral24/KOSTA244_Final#7]
저번에 제가 했는데 어떻게 하는건지 모르겠음 도와주십쇼

**Comment by hyepark0826** [comment]
git clone되고 나서는 메인에서 브랜치/ 브랜치에서 메인으로 옮기는 기능이 생기더라구요! 제가 좀 더 공부해볼게요! 항상 깃 꼼꼼히 올려줘서 감사해용!>_<

**Comment by koeun23** [comment]
git desktop에서  Branch->Merge into current branch 에서 Main으로 설정 후 commit
